# Home Route #
##############

MTIMusicAndMeBundle_homepage:
    pattern:  /
    defaults: { _controller: MTIMusicAndMeBundle:Home:index }


# Account Routes #
##################

MTIMusicAndMeBundle_account:
    pattern:  /account/
    defaults: { _controller: MTIMusicAndMeBundle:Account:index }

MTIMusicAndMeBundle_login:
    pattern:  /account/login/
    defaults: { _controller: MTIMusicAndMeBundle:Account:login }

MTIMusicAndMeBundle_logout:
    pattern:  /account/logout/
    defaults: { _controller: MTIMusicAndMeBundle:Account:logout }

MTIMusicAndMeBundle_create:
    pattern:  /account/create/
    defaults: { _controller: MTIMusicAndMeBundle:Account:create }

MTIMusicAndMeBundle_validate:
    pattern:  /account/validate/
    defaults: { _controller: MTIMusicAndMeBundle:Account:validate }


# Stream Routes #
#################

MTIMusicAndMeBundle_streamIndex:
    pattern:  /stream/
    defaults: { _controller: MTIMusicAndMeBundle:Stream:index }

MTIMusicAndMeBundle_streamCreate:
    pattern:  /stream/create/
    defaults: { _controller: MTIMusicAndMeBundle:Stream:create }

MTIMusicAndMeBundle_streamView:
    pattern:  /stream/{stream_id}
    defaults: { _controller: MTIMusicAndMeBundle:Stream:view, stream_id:-1 }

MTIMusicAndMeBundle_streamVote:
    pattern:  /stream/vote/
    defaults: { _controller: MTIMusicAndMeBundle:Stream:vote, _format: json }
    requirements:
        _format: json
        _method: POST

MTIMusicAndMeBundle_search:
    pattern:  /search/
    defaults: { _controller: MTIMusicAndMeBundle:Search:index }

MTIMusicAndMeBundle_searchZik:
    pattern:  /stream/{stream_id}/search/
    defaults: { _controller: MTIMusicAndMeBundle:SearchZik:index, stream_id:-1 }

# Upload Routes #
#################

MTIMusicAndMeBundle_upload:
    pattern:  /upload/
    defaults: { _controller: MTIMusicAndMeBundle:Upload:index }

# Musiques Routes #
###################

# MTIMusicAndMeBundle_searchZik:
#     pattern:  /searchzik
#     defaults: { _controller: MTIMusicAndMeBundle:SearchZik:index }
