MTIMusicAndMeBundle_hello:
    pattern:  /hello/{name}
    defaults: { _controller: MTIMusicAndMeBundle:Default:index }

MTIMusicAndMeBundle_homepage:
    pattern:  /
    defaults: { _controller: MTIMusicAndMeBundle:Home:index }
