MTIMusicAndMeBundle_hello:
    pattern:  /hello/{name}
    defaults: { _controller: MTIMusicAndMeBundle:Default:index }

MTIMusicAndMeBundle_homepage:
    pattern:  /
    defaults: { _controller: MTIMusicAndMeBundle:Home:index }

MTIMusicAndMeBundle_upload:
    pattern:  /upload
    defaults: { _controller: MTIMusicAndMeBundle:Upload:index }

MTIMusicAndMeBundle_save:
    pattern:  /save
    defaults: { _controller: MTIMusicAndMeBundle:Upload:save }
