# Home Route #
##############

MTIMusicAndMeBundle_homepage:
    pattern:  /
    defaults: { _controller: MTIMusicAndMeBundle:Home:index }


# Account Routes #
##################

MTIMusicAndMeBundle_account:
    pattern:  /account/
    defaults: { _controller: MTIMusicAndMeBundle:Account:index }

MTIMusicAndMeBundle_login:
    pattern:  /account/login/
    defaults: { _controller: MTIMusicAndMeBundle:Account:login }

MTIMusicAndMeBundle_logout:
    pattern:  /account/logout/
    defaults: { _controller: MTIMusicAndMeBundle:Account:logout }

MTIMusicAndMeBundle_create:
    pattern:  /account/create/
    defaults: { _controller: MTIMusicAndMeBundle:Account:create }

MTIMusicAndMeBundle_validate:
    pattern:  /account/validate/
    defaults: { _controller: MTIMusicAndMeBundle:Account:validate }


# Stream Routes #
#################

MTIMusicAndMeBundle_streamIndex:
    pattern:  /stream/
    defaults: { _controller: MTIMusicAndMeBundle:Stream:index }

MTIMusicAndMeBundle_streamCreate:
    pattern:  /stream/create/
    defaults: { _controller: MTIMusicAndMeBundle:Stream:create }
